# Generated by Django 4.2.5 on 2023-09-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_news_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='news',
            name='timestamp',
        ),
    ]
