# Generated by Django 4.2.5 on 2023-09-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_dashboard_timestamp_news_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
