# Generated by Django 4.2.5 on 2023-09-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_cart_items_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='news',
            name='timestamp',
        ),
    ]
