# Generated by Django 4.2.5 on 2023-09-11 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_dashboard_timestamp_news_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
